[package]
name = "aerocaps"
version = "0.0.4"
edition = "2021"

[lib]
name = "rust_nurbs"
crate-type = ["cdylib"]
path = "aerocaps/rust/nurbs.rs"

[dependencies]
pyo3 = "0.23.3"
num-integer = "0.1.46"  # num_integer::binomial used in bernstein_poly
